# Generated by Django 4.1.7 on 2023-02-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Sobrenome',
            new_name='nome_completo',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='telefone',
        ),
    ]
